//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/InputSystem/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""Foot"",
            ""id"": ""d017bb5d-8ff6-4c59-8fba-dabaaf845b4b"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""60aafd47-8be3-4677-ace7-1363aa207b25"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cc6e569d-56f5-436b-a547-03e1d9fe7925"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8445bb93-3df1-496c-8d8a-4f3fb942db6d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""04faa2f2-8125-4bc3-a118-24651ef09c29"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CallDragon"",
                    ""type"": ""Button"",
                    ""id"": ""4259fe48-3e52-4103-89d9-04ae7c15950a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dive"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ac687b31-21cc-441e-bcb6-fd05af2f28d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LookDragon"",
                    ""type"": ""Button"",
                    ""id"": ""20b9523d-b2bc-45be-bbfb-b641dace3f17"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Paravela"",
                    ""type"": ""Button"",
                    ""id"": ""dfd0bfb8-88f1-4e36-a15a-1e27205497eb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LandDragon"",
                    ""type"": ""Button"",
                    ""id"": ""dbdd069c-c408-4a21-bb06-de2f2ce060fd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4599a9b1-8e30-4398-9dfe-52dbed7bc9a1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3dc8584-90b1-43db-b20e-42bd1451a71f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fe4c09b-031c-4c4e-a196-b1899eaa8551"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""ed4bf375-68ec-4bad-9039-21ced873e13f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bea85aee-2605-4fcf-a344-170b726e9193"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e44bc029-3215-4457-bc48-8603f630c2be"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4f0f80e1-ea1f-4464-afbd-8f898e591ad8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""6ad09b2a-f205-4808-8a36-fbf7737c188c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""ae422e2d-b140-4a6d-a4c7-29504384f7aa"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""848a3a99-155e-4927-b128-7ec27a9a7cb0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d8778176-fdc2-4cb0-aee4-7bf8a19684ce"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4d165f47-cee3-490c-b501-61a93e42dde3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""89b0a903-6a55-48e3-840f-8a8378e42b9a"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false)"",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1028088c-b0b4-474b-bf7b-8e0a6dca3019"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a27cca4-ff3b-4534-9fc7-42fdd0078a43"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c87d81a6-f587-472c-a026-1d4ff715c8bf"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0167332b-8c6c-43c2-837f-d87883bc16e0"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CallDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fdc468fc-1167-41af-b16b-fc8a6247a2c8"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CallDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13a6318c-e02b-46bd-907e-fc3ee7864cb8"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e8d9ec0-76a1-4ea1-a7d6-a9254d712134"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dive"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08922969-3f0b-4ed8-a233-57e6f7115673"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6afb643-671f-4a12-a9cb-b01ed2879ca8"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b92751ca-5829-41a2-8ab0-be01b3fb13b2"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paravela"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6445d735-e93b-4f6b-a041-03e3414c5234"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Paravela"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84fae8ff-43eb-4bf7-8dfe-1247f4377454"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LandDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""345c6ce4-9354-4c2d-b439-f24c9a1eaa4b"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LandDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Dragon"",
            ""id"": ""b6863d2e-51bb-4ebd-ba11-87efc995ca6c"",
            ""actions"": [
                {
                    ""name"": ""PitchRoll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9e3524b6-0c63-4784-b196-ff6dd05ce2e4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dismount"",
                    ""type"": ""Button"",
                    ""id"": ""61957cb9-f97e-4dd5-83ea-876d9f2a4daa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DismountJump"",
                    ""type"": ""Button"",
                    ""id"": ""e1680872-6aaa-4697-80dd-e713aac9912b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Accelerate"",
                    ""type"": ""Button"",
                    ""id"": ""57c28e49-3ac4-444f-afb1-ec7f225e22cd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""3008ef14-c1d5-4594-a595-af88e6850e64"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Yaw"",
                    ""type"": ""PassThrough"",
                    ""id"": ""74bb5139-f35f-4f85-8f44-b151e4624f2f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4116aeaa-e429-4e5f-af15-a077789e539c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLanded"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f84a19c1-ff8f-4c19-b4b4-146d6d1a7e0b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeOff"",
                    ""type"": ""Button"",
                    ""id"": ""0a80c458-13dd-4679-ad2c-37cb40b9b353"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""MultiTap(tapCount=5)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LandDragon"",
                    ""type"": ""Button"",
                    ""id"": ""25d4d8cc-7213-49e0-a8fc-b888971d273c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DragonJump"",
                    ""type"": ""Button"",
                    ""id"": ""1e8c4f8d-54c5-4fc8-a7f9-57255be6107a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""83a569dd-a96e-4a4c-ae38-9efcb9ec4a4f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f20c3d65-da2d-4338-a014-76bef5106d4d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f9e70aac-5cb9-40fc-96ac-954ac848c154"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""09f6ffd2-b04e-49ca-a599-bedeedd5f89d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""00e54380-db78-46c9-8c0d-2fea3b603583"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b0da32d6-7039-4b19-b797-502e0a06db6a"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4990af16-4476-4531-aed8-9b771b48ced8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dd3f553b-3718-4c4d-9ab6-2200696fdb95"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""334429b3-de2e-49de-af2e-482a5c375e8e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""63b4f1c4-4214-4db2-9279-13cf19337056"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PitchRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9b88d9ce-9318-477c-9e45-e53364489958"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DismountJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4424552-1e32-432c-aa0f-be77ffe12d44"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DismountJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5a77004-4377-4ddc-8ec3-dfa5f0d031a2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c407747-d014-4a2e-b52b-d8063ae0e691"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42d62090-e67a-46ab-80ae-b09515f9aae9"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a62793c2-a17a-4ed5-8337-6f3eac3322d1"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis Gamepad Shoulders"",
                    ""id"": ""ad346ec5-c62a-48f3-b541-e5d4a86080c4"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a19d452a-8556-47f9-b8c1-9eaded61b774"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2ea358ac-2930-40c6-a0ca-6d199425a472"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis Keyboard"",
                    ""id"": ""cf553650-66a7-496d-9148-b1bb1f70a3cf"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""caf087d7-f680-4122-b9da-15ce5aa9875c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6b0a1f10-91e8-4d3b-8e9c-1ae473b0c519"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e022be93-6418-45c6-85b4-5a692e60d0b6"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""InvertVector2(invertX=false)"",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7f98429-d2fd-4a1d-9620-18eedb4a9700"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4df30c55-1927-4849-92e5-c46c050a6097"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""4bd6b07e-67d9-4aa5-834f-68576ab89125"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8364948f-4b6a-46f6-a33d-24c9ad0b424f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2fef3903-00c1-4326-b493-7bc3587cabfb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b056384a-5866-44c1-9feb-25f7af3a9edf"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f20571e5-48b6-4c3d-9295-3e7209cc6d57"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3baa0ffa-3b96-4d13-a0b1-b2776d0b4c41"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""15ce7d18-cfd5-4dca-9ed7-8bf6a8e96b0f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0c58af0a-4f5b-4c86-be2f-f44583ce5135"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5143a299-15bb-4d84-8f9d-34258b8a01a7"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLanded"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""951f7809-fd4b-4ef5-a4b1-ca6cb8107877"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b414a36-0c3c-4189-bc01-76ac665df768"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeOff"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""546268bf-ee58-4049-9dad-fe09d8a74c71"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LandDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45677596-ae99-466f-a5a2-81606a21d770"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LandDragon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5bf3d59-649a-46be-86db-b4417316712c"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dismount"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04d8e749-a7e0-40db-b5ab-cb56a72e35d1"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dismount"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2be769a2-b031-4ca9-be78-38592cafb291"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragonJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5457b20-d5f5-4b73-a084-92d2e6ed6cd1"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragonJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Foot
        m_Foot = asset.FindActionMap("Foot", throwIfNotFound: true);
        m_Foot_Jump = m_Foot.FindAction("Jump", throwIfNotFound: true);
        m_Foot_Move = m_Foot.FindAction("Move", throwIfNotFound: true);
        m_Foot_Camera = m_Foot.FindAction("Camera", throwIfNotFound: true);
        m_Foot_Run = m_Foot.FindAction("Run", throwIfNotFound: true);
        m_Foot_CallDragon = m_Foot.FindAction("CallDragon", throwIfNotFound: true);
        m_Foot_Dive = m_Foot.FindAction("Dive", throwIfNotFound: true);
        m_Foot_LookDragon = m_Foot.FindAction("LookDragon", throwIfNotFound: true);
        m_Foot_Paravela = m_Foot.FindAction("Paravela", throwIfNotFound: true);
        m_Foot_LandDragon = m_Foot.FindAction("LandDragon", throwIfNotFound: true);
        // Dragon
        m_Dragon = asset.FindActionMap("Dragon", throwIfNotFound: true);
        m_Dragon_PitchRoll = m_Dragon.FindAction("PitchRoll", throwIfNotFound: true);
        m_Dragon_Dismount = m_Dragon.FindAction("Dismount", throwIfNotFound: true);
        m_Dragon_DismountJump = m_Dragon.FindAction("DismountJump", throwIfNotFound: true);
        m_Dragon_Accelerate = m_Dragon.FindAction("Accelerate", throwIfNotFound: true);
        m_Dragon_Brake = m_Dragon.FindAction("Brake", throwIfNotFound: true);
        m_Dragon_Yaw = m_Dragon.FindAction("Yaw", throwIfNotFound: true);
        m_Dragon_Camera = m_Dragon.FindAction("Camera", throwIfNotFound: true);
        m_Dragon_MoveLanded = m_Dragon.FindAction("MoveLanded", throwIfNotFound: true);
        m_Dragon_TakeOff = m_Dragon.FindAction("TakeOff", throwIfNotFound: true);
        m_Dragon_LandDragon = m_Dragon.FindAction("LandDragon", throwIfNotFound: true);
        m_Dragon_DragonJump = m_Dragon.FindAction("DragonJump", throwIfNotFound: true);
    }

    ~@InputActions()
    {
        UnityEngine.Debug.Assert(!m_Foot.enabled, "This will cause a leak and performance issues, InputActions.Foot.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Dragon.enabled, "This will cause a leak and performance issues, InputActions.Dragon.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Foot
    private readonly InputActionMap m_Foot;
    private List<IFootActions> m_FootActionsCallbackInterfaces = new List<IFootActions>();
    private readonly InputAction m_Foot_Jump;
    private readonly InputAction m_Foot_Move;
    private readonly InputAction m_Foot_Camera;
    private readonly InputAction m_Foot_Run;
    private readonly InputAction m_Foot_CallDragon;
    private readonly InputAction m_Foot_Dive;
    private readonly InputAction m_Foot_LookDragon;
    private readonly InputAction m_Foot_Paravela;
    private readonly InputAction m_Foot_LandDragon;
    public struct FootActions
    {
        private @InputActions m_Wrapper;
        public FootActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Foot_Jump;
        public InputAction @Move => m_Wrapper.m_Foot_Move;
        public InputAction @Camera => m_Wrapper.m_Foot_Camera;
        public InputAction @Run => m_Wrapper.m_Foot_Run;
        public InputAction @CallDragon => m_Wrapper.m_Foot_CallDragon;
        public InputAction @Dive => m_Wrapper.m_Foot_Dive;
        public InputAction @LookDragon => m_Wrapper.m_Foot_LookDragon;
        public InputAction @Paravela => m_Wrapper.m_Foot_Paravela;
        public InputAction @LandDragon => m_Wrapper.m_Foot_LandDragon;
        public InputActionMap Get() { return m_Wrapper.m_Foot; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FootActions set) { return set.Get(); }
        public void AddCallbacks(IFootActions instance)
        {
            if (instance == null || m_Wrapper.m_FootActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FootActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @CallDragon.started += instance.OnCallDragon;
            @CallDragon.performed += instance.OnCallDragon;
            @CallDragon.canceled += instance.OnCallDragon;
            @Dive.started += instance.OnDive;
            @Dive.performed += instance.OnDive;
            @Dive.canceled += instance.OnDive;
            @LookDragon.started += instance.OnLookDragon;
            @LookDragon.performed += instance.OnLookDragon;
            @LookDragon.canceled += instance.OnLookDragon;
            @Paravela.started += instance.OnParavela;
            @Paravela.performed += instance.OnParavela;
            @Paravela.canceled += instance.OnParavela;
            @LandDragon.started += instance.OnLandDragon;
            @LandDragon.performed += instance.OnLandDragon;
            @LandDragon.canceled += instance.OnLandDragon;
        }

        private void UnregisterCallbacks(IFootActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @CallDragon.started -= instance.OnCallDragon;
            @CallDragon.performed -= instance.OnCallDragon;
            @CallDragon.canceled -= instance.OnCallDragon;
            @Dive.started -= instance.OnDive;
            @Dive.performed -= instance.OnDive;
            @Dive.canceled -= instance.OnDive;
            @LookDragon.started -= instance.OnLookDragon;
            @LookDragon.performed -= instance.OnLookDragon;
            @LookDragon.canceled -= instance.OnLookDragon;
            @Paravela.started -= instance.OnParavela;
            @Paravela.performed -= instance.OnParavela;
            @Paravela.canceled -= instance.OnParavela;
            @LandDragon.started -= instance.OnLandDragon;
            @LandDragon.performed -= instance.OnLandDragon;
            @LandDragon.canceled -= instance.OnLandDragon;
        }

        public void RemoveCallbacks(IFootActions instance)
        {
            if (m_Wrapper.m_FootActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFootActions instance)
        {
            foreach (var item in m_Wrapper.m_FootActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FootActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FootActions @Foot => new FootActions(this);

    // Dragon
    private readonly InputActionMap m_Dragon;
    private List<IDragonActions> m_DragonActionsCallbackInterfaces = new List<IDragonActions>();
    private readonly InputAction m_Dragon_PitchRoll;
    private readonly InputAction m_Dragon_Dismount;
    private readonly InputAction m_Dragon_DismountJump;
    private readonly InputAction m_Dragon_Accelerate;
    private readonly InputAction m_Dragon_Brake;
    private readonly InputAction m_Dragon_Yaw;
    private readonly InputAction m_Dragon_Camera;
    private readonly InputAction m_Dragon_MoveLanded;
    private readonly InputAction m_Dragon_TakeOff;
    private readonly InputAction m_Dragon_LandDragon;
    private readonly InputAction m_Dragon_DragonJump;
    public struct DragonActions
    {
        private @InputActions m_Wrapper;
        public DragonActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PitchRoll => m_Wrapper.m_Dragon_PitchRoll;
        public InputAction @Dismount => m_Wrapper.m_Dragon_Dismount;
        public InputAction @DismountJump => m_Wrapper.m_Dragon_DismountJump;
        public InputAction @Accelerate => m_Wrapper.m_Dragon_Accelerate;
        public InputAction @Brake => m_Wrapper.m_Dragon_Brake;
        public InputAction @Yaw => m_Wrapper.m_Dragon_Yaw;
        public InputAction @Camera => m_Wrapper.m_Dragon_Camera;
        public InputAction @MoveLanded => m_Wrapper.m_Dragon_MoveLanded;
        public InputAction @TakeOff => m_Wrapper.m_Dragon_TakeOff;
        public InputAction @LandDragon => m_Wrapper.m_Dragon_LandDragon;
        public InputAction @DragonJump => m_Wrapper.m_Dragon_DragonJump;
        public InputActionMap Get() { return m_Wrapper.m_Dragon; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DragonActions set) { return set.Get(); }
        public void AddCallbacks(IDragonActions instance)
        {
            if (instance == null || m_Wrapper.m_DragonActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DragonActionsCallbackInterfaces.Add(instance);
            @PitchRoll.started += instance.OnPitchRoll;
            @PitchRoll.performed += instance.OnPitchRoll;
            @PitchRoll.canceled += instance.OnPitchRoll;
            @Dismount.started += instance.OnDismount;
            @Dismount.performed += instance.OnDismount;
            @Dismount.canceled += instance.OnDismount;
            @DismountJump.started += instance.OnDismountJump;
            @DismountJump.performed += instance.OnDismountJump;
            @DismountJump.canceled += instance.OnDismountJump;
            @Accelerate.started += instance.OnAccelerate;
            @Accelerate.performed += instance.OnAccelerate;
            @Accelerate.canceled += instance.OnAccelerate;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @Yaw.started += instance.OnYaw;
            @Yaw.performed += instance.OnYaw;
            @Yaw.canceled += instance.OnYaw;
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @MoveLanded.started += instance.OnMoveLanded;
            @MoveLanded.performed += instance.OnMoveLanded;
            @MoveLanded.canceled += instance.OnMoveLanded;
            @TakeOff.started += instance.OnTakeOff;
            @TakeOff.performed += instance.OnTakeOff;
            @TakeOff.canceled += instance.OnTakeOff;
            @LandDragon.started += instance.OnLandDragon;
            @LandDragon.performed += instance.OnLandDragon;
            @LandDragon.canceled += instance.OnLandDragon;
            @DragonJump.started += instance.OnDragonJump;
            @DragonJump.performed += instance.OnDragonJump;
            @DragonJump.canceled += instance.OnDragonJump;
        }

        private void UnregisterCallbacks(IDragonActions instance)
        {
            @PitchRoll.started -= instance.OnPitchRoll;
            @PitchRoll.performed -= instance.OnPitchRoll;
            @PitchRoll.canceled -= instance.OnPitchRoll;
            @Dismount.started -= instance.OnDismount;
            @Dismount.performed -= instance.OnDismount;
            @Dismount.canceled -= instance.OnDismount;
            @DismountJump.started -= instance.OnDismountJump;
            @DismountJump.performed -= instance.OnDismountJump;
            @DismountJump.canceled -= instance.OnDismountJump;
            @Accelerate.started -= instance.OnAccelerate;
            @Accelerate.performed -= instance.OnAccelerate;
            @Accelerate.canceled -= instance.OnAccelerate;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @Yaw.started -= instance.OnYaw;
            @Yaw.performed -= instance.OnYaw;
            @Yaw.canceled -= instance.OnYaw;
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @MoveLanded.started -= instance.OnMoveLanded;
            @MoveLanded.performed -= instance.OnMoveLanded;
            @MoveLanded.canceled -= instance.OnMoveLanded;
            @TakeOff.started -= instance.OnTakeOff;
            @TakeOff.performed -= instance.OnTakeOff;
            @TakeOff.canceled -= instance.OnTakeOff;
            @LandDragon.started -= instance.OnLandDragon;
            @LandDragon.performed -= instance.OnLandDragon;
            @LandDragon.canceled -= instance.OnLandDragon;
            @DragonJump.started -= instance.OnDragonJump;
            @DragonJump.performed -= instance.OnDragonJump;
            @DragonJump.canceled -= instance.OnDragonJump;
        }

        public void RemoveCallbacks(IDragonActions instance)
        {
            if (m_Wrapper.m_DragonActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDragonActions instance)
        {
            foreach (var item in m_Wrapper.m_DragonActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DragonActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DragonActions @Dragon => new DragonActions(this);
    public interface IFootActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnCallDragon(InputAction.CallbackContext context);
        void OnDive(InputAction.CallbackContext context);
        void OnLookDragon(InputAction.CallbackContext context);
        void OnParavela(InputAction.CallbackContext context);
        void OnLandDragon(InputAction.CallbackContext context);
    }
    public interface IDragonActions
    {
        void OnPitchRoll(InputAction.CallbackContext context);
        void OnDismount(InputAction.CallbackContext context);
        void OnDismountJump(InputAction.CallbackContext context);
        void OnAccelerate(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnYaw(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnMoveLanded(InputAction.CallbackContext context);
        void OnTakeOff(InputAction.CallbackContext context);
        void OnLandDragon(InputAction.CallbackContext context);
        void OnDragonJump(InputAction.CallbackContext context);
    }
}
